apiVersion: v1
kind: ConfigMap
metadata:
  name: operational-config
  namespace: petroedge
data:
  GRPC_PORT: "50051"
  POOL_SIZE: "10"
---
apiVersion: v1
kind: Secret
metadata:
  name: operational-secret
  namespace: petroedge
stringData:
  DATABASE_URL: postgres://operational:operational_dev@operational-postgres:5432/operational?sslmode=disable