apiVersion: v1
kind: Service
metadata:
  name: operational
  namespace: petroedge
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
  selector:
    service: operational