apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: operational-postgres
  namespace: petroedge
  labels:
    service: operational-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
