apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operational-secret
  namespace: petroedge
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: petroedge-production
    kind: ClusterSecretStore
  target:
    name: operational-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: petroedge/operational/database-url
